apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-b
  labels:
    app: svc-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-b
  template:
    metadata:
      labels:
        app: svc-b
    spec:
      containers:
        - name: svc-b
          image: dakshsawhneyy/demo-service-b:904f795d383cbb61d36ddbce79b7e72e2f5ec7c0
          imagePullPolicy: Always
          ports:
          - containerPort: 9001
          resources:
            requests:
              cpu: "100m" # Request 1/10th of a CPU core
              memory: "128Mi" # Request 128 Mebibytes of memory
            limits:
              memory: "256Mi"
              cpu: "300m"