apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-b
  labels:
    app: svc-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-b
  template:
    metadata:
      labels:
        app: svc-b
    spec:
      containers:
        - name: svc-b
          image: dakshsawhneyy/demo-service-b:ebf1d09bec5e379172ca6e75ffe9b92ff2f0b7e1
          imagePullPolicy: Always
          ports:
            - containerPort: 9001