apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-b
  labels:
    app: svc-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-b
  template:
    metadata:
      labels:
        app: svc-b
    spec:
      containers:
        - name: svc-b
          image: 897722695334.dkr.ecr.ap-south-1.amazonaws.com/god-level-project/service-b:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001