apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
  labels:
    app: svc-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-a
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
        - name: svc-a
          image: dakshsawhneyy/demo-service-a:1c693a56a43434754e349333a291279e3363b4a4
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
          - name: SERVICE_B_URI
            value: "http://svc-b-service:9001"